# Generated by Django 3.0.5 on 2020-04-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200331_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
