# Generated by Django 3.0.5 on 2020-04-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200402_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='title',
        ),
    ]
