# Generated by Django 3.0.5 on 2020-04-02 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200402_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='img_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='title',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
