# Generated by Django 3.0.5 on 2020-04-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20200411_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followed',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='followed',
            name='following',
        ),
        migrations.DeleteModel(
            name='Posted',
        ),
        migrations.DeleteModel(
            name='Followed',
        ),
    ]
